version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: bookstore
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"  # Expose PostgreSQL port
    networks:
      - mynetwork

  flask:
    build: .
    container_name: flask
    depends_on:
      - postgres
    restart: always
    environment:
      POSTGRES_DB: bookstore
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    ports:
      - "5000:5000"  # Expose Flask port
    networks:
      - mynetwork
networks:
  mynetwork:
    driver: bridge


